### ISSUE TITLE
Missing migration (password_resets)

### ISSUE THREAD

**Issue by nils-kt** [LaravelDaily/Laravel-Breeze-Pages-Skeleton#6]
Missing migration for the table "password_resets".

**Comment by krekas** [comment]
@nils-kt don't see where it is in the framework itself or breeze package.

**Comment by nils-kt** [comment]
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.password_resets' doesn't exist (Connection: mysql, SQL: select * from `password_resets` where `email` = test@domain.tld limit 1)
```
https://github.com/LaravelDaily/Laravel-Breeze-Pages-Skeleton/blob/e90e532cffca2d153d31afd3c44b3be4e4a076b1/app/Http/Controllers/Auth/PasswordResetLinkController.php#L35

**Comment by krekas** [comment]
Can you make a pr with the fix? Based on this commit https://github.com/laravel/laravel/commit/a28ad2966df4488c873f793c6e5b03cbea547d1e
